// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnKKzANoNOx9rORpcCe4VXqPULRd2yR8I',
    appId: '1:66148375593:web:45f058693464a98f811038',
    messagingSenderId: '66148375593',
    projectId: 'wasiapp-66023',
    authDomain: 'wasiapp-66023.firebaseapp.com',
    storageBucket: 'wasiapp-66023.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZLhoqC4yiDs5BNzi5rsTk5qck65Q3T7s',
    appId: '1:66148375593:android:8fa0c5daed85bd06811038',
    messagingSenderId: '66148375593',
    projectId: 'wasiapp-66023',
    storageBucket: 'wasiapp-66023.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1_cxYHk5q3zWZ0l1QknCtLKMmdBpkxoI',
    appId: '1:66148375593:ios:c97017b8a758e8b2811038',
    messagingSenderId: '66148375593',
    projectId: 'wasiapp-66023',
    storageBucket: 'wasiapp-66023.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1_cxYHk5q3zWZ0l1QknCtLKMmdBpkxoI',
    appId: '1:66148375593:ios:c97017b8a758e8b2811038',
    messagingSenderId: '66148375593',
    projectId: 'wasiapp-66023',
    storageBucket: 'wasiapp-66023.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnKKzANoNOx9rORpcCe4VXqPULRd2yR8I',
    appId: '1:66148375593:web:db125250a1c9f680811038',
    messagingSenderId: '66148375593',
    projectId: 'wasiapp-66023',
    authDomain: 'wasiapp-66023.firebaseapp.com',
    storageBucket: 'wasiapp-66023.firebasestorage.app',
  );
}
